### ISSUE TITLE
Version 1.0.0 Task List

### ISSUE THREAD

**Issue by shinokada** [themesberg/flowbite-svelte#1011]
Please contribute additional items to this thread. Provide specific details such as component names, required props, and more. 

- [ ] inconsistent props like indicatorDivClass 
- [ ] cleanup redundant components/wrappers instead of the use of existing ones (the latest ChartWrapper instead of Card). 
- [ ] With the introduction of twMerge there's no longer a need for the defaultClass prop existing in many components.
- [ ] themes mechanism: styling and colors.
