### ISSUE TITLE
Update default colors of components to orange/primary

### ISSUE THREAD

**Issue by zoltanszogyenyi** [themesberg/flowbite-svelte#744]
## Summary

It would be great if we updated all the default colors of the components from blue to orange (or as close to primary as possible).

This would greatly improve the visual impact of the component library in accordance with the new docs layout.

### Basic example

For example, here's how the cards looks now:

<img width="877" alt="Screenshot 2023-05-09 at 11 46 09" src="https://user-images.githubusercontent.com/8052108/237043980-89c7feb6-9383-4ff0-b24d-32c5f4409a3f.png">

How it would look better in the context of Flowbite Svelte:

<img width="898" alt="Screenshot 2023-05-09 at 11 50 43" src="https://user-images.githubusercontent.com/8052108/237045121-d292df62-7e25-4f03-a381-f56663c30c86.png">

For this to take place I updated the `Button.svelte` code:

```
| 'redToYellow' = group ? (outline ? 'dark' : 'alternative') : 'primary'; // primary as fallback
```

Of course, we would have to update the `tailwind.config.js` file to automatically set the primary color via the Flowbite plugin or at least clearly document this via the `theming` documentation for colors.

Ideally, we could also use the the Flowbite Svelte CLI issue (https://github.com/themesberg/flowbite-svelte/issues/723) to update the `tailwind.config.js` file of the user with the default primary colors and other settings.

### Motivation

It would greatly improve the look and feel of the component library and we should make it easier for users to use a `primary` color across their application for better theming experience as opposed to just flat colors - we should still keep that feature available but we should shift to using `primary`, `secondary`, `light`, `dark` colors.

**Comment by shinokada** [comment]
I also update [the docs](https://github.com/themesberg/flowbite-svelte/pull/747).

**Comment by shinokada** [comment]
We need to apply primary color to checkbox and radio components as well.

**Comment by zoltanszogyenyi** [comment]
> We need to apply primary color to checkbox, range, select, textarea, toggle and radio components as well.

Hello @shinokada - the change is great! As you've said, we need to apply this to the other components too.

I think we can keep this issue open as a "parent" issue until all of these are solved.

Quick question - does the primary color work out of the box when installing `flowbite-svelte` or do the users need to set the primary colors manually inside the `tailwind.config.js` file? Asking this to make sure that it's documented.

Cheers,
Zoltan

**Comment by shinokada** [comment]
You need to set the primary color. I explained on quickstart and introduction pages.

**Comment by shinokada** [comment]
## Todo list

- [ ] [Stepper indicator](https://flowbite-svelte.com/docs/components/indicators#Stepper_indicator)
- [ ] [Range](https://flowbite-svelte.com/docs/forms/range)
- [ ] [Select](https://flowbite-svelte.com/docs/forms/select)
- [ ] [Textarea](https://flowbite-svelte.com/docs/forms/textarea)
- [ ] [Toggle](https://flowbite-svelte.com/docs/forms/toggle)
- [ ] [Radio](https://flowbite-svelte.com/docs/forms/radio)
- [ ] [Banner page](https://flowbite-svelte.com/docs/components/banner#Newsletter_sign-up_banner)
- [ ] [List group page](https://flowbite-svelte.com/docs/components/list-group#List_group_with_links)
- [ ] [Progressbar](https://flowbite-svelte.com/docs/components/progress)
- [ ] [Score rating](https://flowbite-svelte.com/docs/components/rating#Score_rating)
- [ ] [Speeddial](https://flowbite-svelte.com/docs/components/speed-dial)
- [ ] [Default spinner](https://flowbite-svelte.com/docs/components/spinner#Default_spinner)
- [ ] [Tab](https://flowbite-svelte.com/docs/components/tab)
- [ ] [Timeline](https://flowbite-svelte.com/docs/components/timeline)
- [ ] [Toast](https://flowbite-svelte.com/docs/components/toast)
- [ ] Change Flowbite blue logo in examples to Flowbite Svelte

**Comment by jjagielka** [comment]
I don't like that solution with the modification of the `tailwind.config.js`. 
Try to use the `<Button>Default</Button>` in REPL. You can be surprised.

**Comment by shinokada** [comment]
@jjagielka Do you have any suggestions?

**Comment by Daschi1** [comment]
@shinokada  Is it maybe possible to define the primary color, if not explicitly set in the config, as blue? `<Button>Default</Button>` would now be blue by default, as it was before this change. I myself was quite confused after updating to the newest version why all my buttons were no longer blue but white, and it took me a while to get behind the reason.

**Comment by Daschi1** [comment]
@shinokada Thank you, I defined the primary color as blue in the `tailwind.config.cjs` file and now it works again. I appreciate your quick response!
