### ISSUE TITLE
Migrate to svelte@4.0.0

### ISSUE THREAD

**Issue by ezegrosfeld** [themesberg/flowbite-svelte#873]
## Summary

Migrate to [Svelte 4](https://github.com/sveltejs/svelte/releases/tag/svelte%404.0.0) following the [migration guide](https://svelte.dev/docs/v4-migration-guide).

In order to test 4.0.0 run:
```shell
npx svelte-migrate@latest svelte-4
``` 

## A11y ARIA warnings
While testing it I get the following warnings:
```shell
app:dev: 20:03:50 [vite-plugin-svelte] /forms/MultiSelect.svelte:53:10 A11y: <svg> with click handler must have an ARIA role
app:dev: 20:03:50 [vite-plugin-svelte] /forms/MultiSelect.svelte:106:8 A11y: <div> with click handler must have an ARIA role
app:dev: 20:03:50 [vite-plugin-svelte] /forms/MultiSelect.svelte:43:0 A11y: <div> with click handler must have an ARIA role
app:dev: 20:03:50 [vite-plugin-svelte] /modals/Modal.svelte:127:8 A11y: Non-interactive element <div> should not be assigned mouse or keyboard event listeners.
app:dev: 20:03:50 [vite-plugin-svelte] /modals/Modal.svelte:92:2 A11y: Non-interactive element <div> should not be assigned mouse or keyboard event listeners.
app:dev: 20:03:50 [vite-plugin-svelte] /paginations/PaginationItem.svelte:22:0 A11y: <svelte:element> with click, keydown, keypress, keyup, mouseenter, mouseleave, mouseover handlers must have an ARIA role
app:dev: 20:03:50 [vite-plugin-svelte] /utils/Frame.svelte:87:2 A11y: <svelte:element> with click, mouseenter, mouseleave handlers must have an ARIA role
app:dev: 20:03:50 [vite-plugin-svelte] /utils/Frame.svelte:102:2 A11y: <svelte:element> with click, mouseenter, mouseleave handlers must have an ARIA role
app:dev: 20:04:10 [vite-plugin-svelte] /buttons/Button.svelte:79:0 A11y: <svelte:element> with click, keydown, keyup, mouseenter, mouseleave handlers must have an ARIA role
```

When building:
```shell
[vite-plugin-svelte] /src/lib/navbar/SidebarMenu.svelte:24:0 A11y: <svg> with click handler must have an ARIA role
[vite-plugin-svelte] /src/routes/docs/+layout.svelte:73:0 A11y: <div> with click, keydown handlers must have an ARIA role
```

## Todos
- [x] Upgrade dependencies
- [x] MultiSelect.svelte:53:10 A11y: <svg> with click handler must have an ARIA role
- [x] MultiSelect.svelte:106:8 A11y: <div> with click handler must have an ARIA role
- [x] MultiSelect.svelte:43:0 A11y: <div> with click handler must have an ARIA role
- [x] Modal.svelte:127:8 A11y: Non-interactive element <div> should not be assigned mouse or keyboard event listeners.
- [x] Modal.svelte:92:2 A11y: Non-interactive element <div> should not be assigned mouse or keyboard event listeners.
- [x] PaginationItem.svelte:22:0 A11y: <svelte:element> with click, keydown, keypress, keyup, mouseenter, mouseleave, mouseover handlers must have an ARIA role.
- [x] Frame.svelte:87:2 A11y: <svelte:element> with click, mouseenter, mouseleave handlers must have an ARIA role.
- [x] Frame.svelte:102:2 A11y: <svelte:element> with click, mouseenter, mouseleave handlers must have an ARIA role.
- [x] Button.svelte:79:0 A11y: <svelte:element> with click, keydown, keyup, mouseenter, mouseleave handlers must have an ARIA role.
- [x] routes/docs/+layout.svelte:73:0 A11y: <div> with click, keydown handlers must have an ARIA role
- [x] src/lib/navbar/SidebarMenu.svelte:24:0 A11y: <svg> with click handler must have an ARIA role

I've seen improvements in https://github.com/themesberg/flowbite-svelte/issues/813 and some warnings already pointed out. However, it is related to the pre-release.
